nav:
  Home: /
  Writing: /blog/
  Podcast: http://ruminatepodcast.com
  Projects: /projects/
  Twitter: https://twitter.com/rmlewisuk

footer:
  Contact: /contact/
  RSS: /feed.xml

projects_url: http://github.com/rmlewisuk

customize:
    gravatar:
        email: 
    logo:
        enabled: false
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
    show_all_posts: false
    post_count: 4
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
