
# html lang
language: en

# main menu navigation
menu:
  Home: /
  Blog: /blog
  Contact: /contact

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/rldm.css

# scripts loaded in the end of the body
scripts:
- /js/rldm.js
